/**
 * Plan Artifact Generator - SpecFirst 3.0
 * 
 * Generates plan.md artifacts with ADRs, implementation phases,
 * testing strategy, and risk matrix.
 * 
 * @module artifacts/plan
 * @version 3.0.0
 */

import type { 
  PlanArtifact, 
  ADR, 
  ImplementationPhase, 
  TestingStrategy,
  Risk,
  Dependency 
} from "./types";

/**
 * Generates YAML frontmatter for plan artifact.
 */
function generateFrontmatter(featureName: string): string {
  const now = new Date().toISOString().split("T")[0];
  
  return `---
feature: ${featureName}
phase: plan
status: draft
created: ${now}
based_on: spec.md
version: 1.0.0
---`;
}

/**
 * Generates an ADR section.
 */
function generateADR(adr: ADR): string {
  const alternatives = adr.alternatives
    .map(a => `- **${a.name}:** ${a.reason}`)
    .join("\n");
  
  const consequences = adr.consequences
    .map(c => `- ${c}`)
    .join("\n");
  
  return `### ${adr.id}: ${adr.title}

**Status:** ${adr.status}
**Date:** ${adr.date}

**Context:**
${adr.context}

**Decision:**
${adr.decision}

**Rationale:**
${adr.rationale}

**Alternatives Considered:**
${alternatives}

**Consequences:**
${consequences}`;
}

/**
 * Generates an implementation phase section.
 */
function generatePhase(phase: ImplementationPhase): string {
  const deliverables = phase.deliverables
    .map(d => `- ${d}`)
    .join("\n");
  
  const criteria = phase.acceptanceCriteria
    .map(c => `- ${c}`)
    .join("\n");
  
  const deps = phase.dependencies.length > 0
    ? phase.dependencies.map(d => `- ${d}`).join("\n")
    : "- None";
  
  const risks = phase.risks.length > 0
    ? phase.risks.map(r => `- ${r}`).join("\n")
    : "- None identified";
  
  return `### Phase ${phase.number}: ${phase.name}

**Objective:** ${phase.objective}

**Deliverables:**
${deliverables}

**Acceptance Criteria:**
${criteria}

**Dependencies:**
${deps}

**Risks:**
${risks}

**Estimated Effort:** ${phase.estimatedEffort}`;
}

/**
 * Generates testing strategy section.
 */
function generateTestingStrategy(strategy: TestingStrategy): string {
  return `### Test Pyramid

| Level | Approach | Coverage Target |
|-------|----------|-----------------|
| Unit Tests | ${strategy.unitTests} | ${strategy.coverageTarget} |
| Integration Tests | ${strategy.integrationTests} | - |
| E2E Tests | ${strategy.e2eTests} | - |
| Performance Tests | ${strategy.performanceTests} | - |`;
}

/**
 * Generates risk matrix table.
 */
function generateRiskMatrix(risks: Risk[]): string {
  if (risks.length === 0) {
    return "| ID | Risk | Probability | Impact | Mitigation |\n|---|---|---|---|---|\n| - | No risks identified | - | - | - |";
  }
  
  const header = "| ID | Risk | Probability | Impact | Mitigation |\n|---|---|---|---|---|";
  const rows = risks
    .map(r => `| ${r.id} | ${r.description} | ${r.probability.toUpperCase()} | ${r.impact.toUpperCase()} | ${r.mitigation} |`)
    .join("\n");
  
  return `${header}\n${rows}`;
}

/**
 * Generates dependencies section.
 */
function generateDependencies(deps: Dependency[]): string {
  if (deps.length === 0) {
    return "| Dependency | Type | Risk | Mitigation |\n|---|---|---|---|\n| None | - | - | - |";
  }
  
  const header = "| Dependency | Type | Risk | Mitigation |\n|---|---|---|---|";
  const rows = deps
    .map(d => `| ${d.name} | ${d.type} | ${d.risk.toUpperCase()} | ${d.mitigation} |`)
    .join("\n");
  
  return `${header}\n${rows}`;
}

/**
 * Generates a complete plan.md artifact.
 */
export function generatePlan(
  featureName: string,
  executiveSummary: string,
  adrs: ADR[],
  phases: ImplementationPhase[],
  testingStrategy: TestingStrategy,
  risks: Risk[],
  dependencies: Dependency[],
  rollbackProcedures: string
): string {
  const frontmatter = generateFrontmatter(featureName);
  const adrSections = adrs.map(generateADR).join("\n\n---\n\n");
  const phaseSections = phases.map(generatePhase).join("\n\n---\n\n");
  const testingSection = generateTestingStrategy(testingStrategy);
  const riskTable = generateRiskMatrix(risks);
  const depsTable = generateDependencies(dependencies);
  
  return `${frontmatter}

# ${featureName} - Implementation Plan

**Version:** 1.0.0
**Status:** Draft

---

## Executive Summary

${executiveSummary}

---

## Architecture Decision Records (ADRs)

${adrSections}

---

## Implementation Phases

${phaseSections}

---

## Testing Strategy

${testingSection}

---

## Risk Matrix

${riskTable}

---

## Dependencies

${depsTable}

---

## Rollback Procedures

${rollbackProcedures}

---

*Generated by SpecFirst 3.0*
`;
}

/**
 * Creates a minimal plan template for user to fill in.
 */
export function createPlanTemplate(featureName: string): string {
  const frontmatter = generateFrontmatter(featureName);
  
  return `${frontmatter}

# ${featureName} - Implementation Plan

**Version:** 1.0.0
**Status:** Draft

---

## Executive Summary

[Brief overview of the implementation approach, timeline, and key milestones]

---

## Architecture Decision Records (ADRs)

### ADR-001: [Decision Title]

**Status:** Proposed
**Date:** [Date]

**Context:**
[What is the issue we're deciding on?]

**Decision:**
[What is the change we're proposing?]

**Rationale:**
[Why is this the best option?]

**Alternatives Considered:**
- **[Alternative 1]:** [Why rejected]
- **[Alternative 2]:** [Why rejected]

**Consequences:**
- [Consequence 1]
- [Consequence 2]

---

## Implementation Phases

### Phase 1: [Name]

**Objective:** [What this phase accomplishes]

**Deliverables:**
- [Deliverable 1]
- [Deliverable 2]

**Acceptance Criteria:**
- [Criterion 1]
- [Criterion 2]

**Dependencies:**
- [Dependency]

**Risks:**
- [Risk]

**Estimated Effort:** [X days]

---

## Testing Strategy

| Level | Approach | Coverage Target |
|-------|----------|-----------------|
| Unit Tests | [Approach] | 80% |
| Integration Tests | [Approach] | - |
| E2E Tests | [Approach] | - |
| Performance Tests | [Approach] | - |

---

## Risk Matrix

| ID | Risk | Probability | Impact | Mitigation |
|---|---|---|---|---|
| R-001 | [Risk description] | LOW/MED/HIGH | LOW/MED/HIGH | [Mitigation] |

---

## Dependencies

| Dependency | Type | Risk | Mitigation |
|---|---|---|---|
| [Dependency] | Internal/External | LOW/MED/HIGH | [Mitigation] |

---

## Rollback Procedures

[Document how to rollback if something goes wrong]

---

*Generated by SpecFirst 3.0*
`;
}

/**
 * Validates a plan artifact structure.
 */
export function validatePlan(content: string): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  
  // Check for frontmatter
  if (!content.startsWith("---")) {
    errors.push("Missing YAML frontmatter");
  }
  
  // Check for required sections
  const requiredSections = [
    "Executive Summary",
    "Implementation Phases",
    "Testing Strategy",
    "Risk Matrix",
  ];
  
  for (const section of requiredSections) {
    if (!content.includes(`## ${section}`)) {
      errors.push(`Missing required section: ${section}`);
    }
  }
  
  // Check for at least one phase
  if (!content.includes("### Phase")) {
    errors.push("Missing implementation phases (need at least one ### Phase section)");
  }
  
  return {
    valid: errors.length === 0,
    errors,
  };
}

// Export for testing
export const __testing = {
  generateFrontmatter,
  generateADR,
  generatePhase,
  generateTestingStrategy,
  generateRiskMatrix,
};
