/**
 * Proposal Artifact Generator - SpecFirst 3.0
 * 
 * Generates proposal.md artifacts with valid YAML frontmatter.
 * 
 * @module artifacts/proposal
 * @version 3.0.0
 */

import type { ProposalArtifact, SolutionApproach } from "./types";

/**
 * Generates YAML frontmatter for proposal artifact.
 */
function generateFrontmatter(featureName: string): string {
  const now = new Date().toISOString().split("T")[0];
  
  return `---
feature: ${featureName}
phase: propose
status: draft
created: ${now}
version: 1.0.0
---`;
}

/**
 * Generates a solution approach section.
 */
function generateApproachSection(approach: SolutionApproach, index: number): string {
  const letter = String.fromCharCode(65 + index); // A, B, C...
  
  const pros = approach.pros.map(p => `- ${p}`).join("\n");
  const cons = approach.cons.map(c => `- ${c}`).join("\n");
  
  return `### Option ${letter}: ${approach.name}

${approach.description}

**Pros:**
${pros}

**Cons:**
${cons}`;
}

/**
 * Generates a complete proposal.md artifact.
 */
export function generateProposal(
  featureName: string,
  problemStatement: string,
  approaches: SolutionApproach[],
  recommendedApproach: string,
  antiPatterns: string[] = [],
  openQuestions: string[] = []
): string {
  const frontmatter = generateFrontmatter(featureName);
  
  const approachSections = approaches
    .map((a, i) => generateApproachSection(a, i))
    .join("\n\n");
  
  const antiPatternsList = antiPatterns.length > 0
    ? antiPatterns.map(ap => `- ${ap}`).join("\n")
    : "- None identified yet";
  
  const openQuestionsList = openQuestions.length > 0
    ? openQuestions.map(q => `- ${q}`).join("\n")
    : "";
  
  const openQuestionsSection = openQuestionsList
    ? `\n\n## Open Questions\n\n${openQuestionsList}`
    : "";
  
  return `${frontmatter}

# ${featureName} - Proposal

## Problem Statement

${problemStatement}

## Solution Approaches

${approachSections}

## Recommended Approach

${recommendedApproach}

## Anti-Patterns to Avoid

${antiPatternsList}${openQuestionsSection}

---

*Generated by SpecFirst 3.0*
`;
}

/**
 * Creates a minimal proposal template for user to fill in.
 */
export function createProposalTemplate(featureName: string): string {
  const frontmatter = generateFrontmatter(featureName);
  
  return `${frontmatter}

# ${featureName} - Proposal

## Problem Statement

[Describe the problem this feature solves. What pain point exists? Why is this needed?]

## Solution Approaches

### Option A: [Name]

[Description of the approach]

**Pros:**
- [Pro 1]
- [Pro 2]

**Cons:**
- [Con 1]
- [Con 2]

### Option B: [Name]

[Description of alternative approach]

**Pros:**
- [Pro 1]
- [Pro 2]

**Cons:**
- [Con 1]
- [Con 2]

## Recommended Approach

[Which option do you recommend and why? Include rationale based on trade-offs.]

## Anti-Patterns to Avoid

- [Anti-pattern 1: Why it would be bad]
- [Anti-pattern 2: Why it would be bad]

## Open Questions

- [Question 1]
- [Question 2]

---

*Generated by SpecFirst 3.0*
`;
}

/**
 * Validates a proposal artifact structure.
 */
export function validateProposal(content: string): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  
  // Check for frontmatter
  if (!content.startsWith("---")) {
    errors.push("Missing YAML frontmatter");
  }
  
  // Check for required sections
  const requiredSections = [
    "Problem Statement",
    "Solution Approaches", 
    "Recommended Approach",
  ];
  
  for (const section of requiredSections) {
    if (!content.includes(`## ${section}`)) {
      errors.push(`Missing required section: ${section}`);
    }
  }
  
  // Check for at least one solution approach
  if (!content.includes("### Option")) {
    errors.push("Missing solution approaches (need at least one ### Option section)");
  }
  
  return {
    valid: errors.length === 0,
    errors,
  };
}

// Export for testing
export const __testing = {
  generateFrontmatter,
  generateApproachSection,
};
