/**
 * Spec Artifact Generator - SpecFirst 3.0
 * 
 * Generates spec.md artifacts with functional requirements,
 * non-functional requirements, user stories, and success criteria.
 * 
 * @module artifacts/spec
 * @version 3.0.0
 */

import type { 
  SpecArtifact, 
  FunctionalRequirement, 
  NonFunctionalRequirement,
  UserStory,
  SuccessCriterion 
} from "./types";

/**
 * Generates YAML frontmatter for spec artifact.
 */
function generateFrontmatter(featureName: string, milestone?: string): string {
  const now = new Date().toISOString().split("T")[0];
  
  const milestoneField = milestone ? `\nmilestone: ${milestone}` : "";
  
  return `---
feature: ${featureName}
phase: specify
status: draft
created: ${now}
based_on: proposal.md
version: 1.0.0${milestoneField}
---`;
}

/**
 * Generates functional requirements table.
 */
function generateFRTable(requirements: FunctionalRequirement[]): string {
  if (requirements.length === 0) {
    return "| ID | Requirement | Priority | Verification |\n|---|---|---|---|\n| - | No requirements defined | - | - |";
  }
  
  const header = "| ID | Requirement | Priority | Verification |\n|---|---|---|---|";
  const rows = requirements
    .map(r => `| ${r.id} | ${r.description} | ${r.priority.toUpperCase()} | ${r.verificationMethod} |`)
    .join("\n");
  
  return `${header}\n${rows}`;
}

/**
 * Generates non-functional requirements table.
 */
function generateNFRTable(requirements: NonFunctionalRequirement[]): string {
  if (requirements.length === 0) {
    return "| ID | Requirement | Metric | Target |\n|---|---|---|---|\n| - | No NFRs defined | - | - |";
  }
  
  const header = "| ID | Requirement | Metric | Target |\n|---|---|---|---|";
  const rows = requirements
    .map(r => `| ${r.id} | ${r.description} | ${r.metric} | ${r.target} |`)
    .join("\n");
  
  return `${header}\n${rows}`;
}

/**
 * Generates user story section.
 */
function generateUserStory(story: UserStory): string {
  return `### ${story.id}: ${story.title}

**Given:** ${story.given}
**When:** ${story.when}
**Then:** ${story.then}`;
}

/**
 * Generates success criteria table.
 */
function generateSCTable(criteria: SuccessCriterion[]): string {
  if (criteria.length === 0) {
    return "| ID | Criterion | Verification |\n|---|---|---|\n| - | No criteria defined | - |";
  }
  
  const header = "| ID | Criterion | Verification |\n|---|---|---|";
  const rows = criteria
    .map(c => `| ${c.id} | ${c.description} | ${c.verificationMethod} |`)
    .join("\n");
  
  return `${header}\n${rows}`;
}

/**
 * Generates a complete spec.md artifact.
 */
export function generateSpec(
  featureName: string,
  frs: FunctionalRequirement[],
  nfrs: NonFunctionalRequirement[],
  userStories: UserStory[],
  successCriteria: SuccessCriterion[],
  architectureDiagram?: string,
  milestone?: string
): string {
  const frontmatter = generateFrontmatter(featureName, milestone);
  const frTable = generateFRTable(frs);
  const nfrTable = generateNFRTable(nfrs);
  const stories = userStories.map(generateUserStory).join("\n\n");
  const scTable = generateSCTable(successCriteria);
  
  const archSection = architectureDiagram
    ? `\n\n## Architecture\n\n${architectureDiagram}`
    : "";
  
  return `${frontmatter}

# ${featureName} - Specification

**Version:** 1.0.0
**Status:** Draft

---

## Functional Requirements

${frTable}

## Non-Functional Requirements

${nfrTable}

## User Stories

${stories}

## Success Criteria

${scTable}${archSection}

---

*Generated by SpecFirst 3.0*
`;
}

/**
 * Creates a minimal spec template for user to fill in.
 */
export function createSpecTemplate(featureName: string): string {
  const frontmatter = generateFrontmatter(featureName);
  
  return `${frontmatter}

# ${featureName} - Specification

**Version:** 1.0.0
**Status:** Draft

---

## Functional Requirements

| ID | Requirement | Priority | Verification |
|---|---|---|---|
| FR-001 | [Requirement description] | MUST | [How to verify] |
| FR-002 | [Requirement description] | SHOULD | [How to verify] |

## Non-Functional Requirements

| ID | Requirement | Metric | Target |
|---|---|---|---|
| NFR-001 | [Performance/security/etc requirement] | [Metric] | [Target value] |

## User Stories

### US-001: [Story Title]

**Given:** [Initial context]
**When:** [Action taken]
**Then:** [Expected outcome]

### US-002: [Story Title]

**Given:** [Initial context]
**When:** [Action taken]
**Then:** [Expected outcome]

## Success Criteria

| ID | Criterion | Verification |
|---|---|---|
| SC-001 | [Success criterion] | [How to verify] |
| SC-002 | [Success criterion] | [How to verify] |

## Architecture

[ASCII diagram or Mermaid diagram showing system architecture]

\`\`\`
┌─────────────┐     ┌─────────────┐
│  Component  │────▶│  Component  │
└─────────────┘     └─────────────┘
\`\`\`

---

*Generated by SpecFirst 3.0*
`;
}

/**
 * Validates a spec artifact structure.
 */
export function validateSpec(content: string): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  
  // Check for frontmatter
  if (!content.startsWith("---")) {
    errors.push("Missing YAML frontmatter");
  }
  
  // Check for required sections
  const requiredSections = [
    "Functional Requirements",
    "Non-Functional Requirements",
    "User Stories",
    "Success Criteria",
  ];
  
  for (const section of requiredSections) {
    if (!content.includes(`## ${section}`)) {
      errors.push(`Missing required section: ${section}`);
    }
  }
  
  // Check for at least one FR
  if (!content.match(/FR-\d{3}/)) {
    errors.push("Missing functional requirements (need at least one FR-XXX)");
  }
  
  // Check for at least one user story
  if (!content.match(/US-\d{3}/)) {
    errors.push("Missing user stories (need at least one US-XXX)");
  }
  
  return {
    valid: errors.length === 0,
    errors,
  };
}

// Export for testing
export const __testing = {
  generateFrontmatter,
  generateFRTable,
  generateNFRTable,
  generateUserStory,
  generateSCTable,
};
